/**
 * flutter / Flutter SSL Pinning Bypass
 * Auto-generated by flutter_ssl_pinning.py
 * Generated at    : 2026-03-09T05:04:56.178265+00:00
 * Recon run at    : 2026-03-09T05:04:55.676081+00:00
 * Binary          : libflutter.so
 * Language        : AARCH64:LE:64:v8A
 * Image base      : 0x00100000
 *
 * Candidate functions discovered by PyGhidra recon:
 *   FUN_00c106d0  RVA=0xb106d0  params=3
 *     void FUN_00c106d0(long param_1,long *param_2,undefined1 *param_3);
 *
 * Hook logic: patch retval → ptr(1)  (= SSL_VERIFY_OK / success)
 */

"use strict";

// --- configuration -----------------------------------------------------------
var TARGET_MODULE = "libflutter.so";
// flutter bundles patched Dart code in libapp.so but the BoringSSL/Flutter
// SSL engine lives in libflutter.so.  Change TARGET_MODULE if your build
// places the SSL code elsewhere.

// --- candidate table (auto-filled by in-memory PyGhidra recon) ---------------
var HOOK_CANDIDATES = [
  { name: "FUN_00c106d0", rva: "0xb106d0", params: 3, sig: "void FUN_00c106d0(long param_1,long *param_2,undefined1 *param_3);" }
];

// --- hook implementation -----------------------------------------------------
function hookCandidate(mod, candidate) {
    var addr = mod.base.add(candidate.rva);
    var modEnd = mod.base.add(mod.size);
    if (addr.compare(modEnd) >= 0) {
        console.log("[-] " + candidate.name + ": RVA " + candidate.rva +
                    " outside module bounds – skipping");
        return;
    }
    console.log("[*] Hooking " + candidate.name +
                "  RVA=" + candidate.rva + "  addr=" + addr);
    try {
        Interceptor.attach(addr, {
            onEnter: function (args) {
                this._name = candidate.name;
            },
            onLeave: function (retval) {
                console.log("[+] " + this._name +
                            " retval " + retval + " → patching to 1 (bypass)");
                retval.replace(ptr(1));
            }
        });
        console.log("[+] " + candidate.name + " hooked successfully");
    } catch (e) {
        console.log("[-] Failed to hook " + candidate.name + ": " + e.message);
    }
}

// --- entry point -------------------------------------------------------------
function bypassSslPinning() {
    console.log("=== flutter / Flutter SSL Pinning Bypass ===");
    console.log("[*] Looking for module: " + TARGET_MODULE);

    var mod = Process.findModuleByName(TARGET_MODULE);
    if (!mod) {
        console.log("[-] " + TARGET_MODULE + " not found in process.");
        console.log("[*] Loaded modules:");
        Process.enumerateModules().forEach(function (m) {
            console.log("    " + m.name + "  base=" + m.base + "  size=" + m.size);
        });
        return;
    }

    console.log("[+] Found " + TARGET_MODULE +
                "  base=" + mod.base + "  size=0x" + mod.size.toString(16));
    console.log("[*] Hooking " + HOOK_CANDIDATES.length + " candidate(s)...");

    HOOK_CANDIDATES.forEach(function (c) {
        hookCandidate(mod, c);
    });

    console.log("[+] SSL pinning bypass armed.");
}

// Slight delay so the module is fully mapped before attaching.
setTimeout(bypassSslPinning, 1000);
